#!/usr/bin/python3
import os
import urllib.parse
import json
import sys
sys.path.append("..")
from magdex import magazine
from magdex import frontpage


#URL to magazines (tells the frontpage how to construct a magazine link). Actual mag link 
#will be substituted into the [] sections
magazine_url = "[SECTION]/[MAG].html"

# Path to root folder where magazine folders are		
magazine_root = "magazines"

def head(): 
	return """<!DOCTYPE html>\n
		<html>\n<head>
		<link rel="stylesheet" href="http://mitsfs.mit.edu/static/css/main.bdbe7b61a7bbc1d899d2d4c72c413f96.css">
  		<style>td {padding: 15px;} th {padding: 15px;}</style>
		</head>\n<body>"""


def foot():
	return "</body>\n</html>"



with open("static/index.hml", "w") as f:
	f.write (head())
	f.write (frontpage.createFrontpage(magazine_root + "/", magazine_url))
	f.write (foot())


for section in [x for x in frontpage.SECTIONS.keys() if not x.endswith(".json")]:
	directory = magazine_root + "/" + section
	magazines = sorted([x for x in os.listdir(directory) if x.endswith(".json")], \
							key=str.casefold)
	os.makedirs("static/" + section, exist_ok=True)
	for mag in magazines:
		#strip .json off the magazine
		mag = mag[:-5]
		with open("static/%s/%s.html" % (section, mag), "w") as f:
			f.write (head())
			f.write ("<a href=\"../index.html\">Back</a>\n")
			f.write (magazine.createMagazine(section, mag, magazine_root))
			f.write (foot())


